MunicipalityCardPrinting/WebApplication2/Controllers/DartaChalaniController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Business.Exceptions;
using Business.Services.Interface;
using DTO;
using DTO.Enums;
using Infrastructure.Database.Models;
using Infrastructure.Repositories.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MunicipalityCardPrinting.Utils;

namespace MunicipalityCardPrinting.Controllers
{
    [Authorize]
    public class DartaChalaniController : Controller
    {
        private readonly IBaseRepository<Darta> _dartaRepo;
        private readonly IBaseRepository<Chalani> _chalaniRepo;
        private readonly IAddressService _addressService;
        private readonly IBaseRepository<ApplicationUser> _userRepo;
        private readonly IDartaChalaniService _dartaChalaniService;
        private readonly IFileHelper _fileHelper;
       

        public DartaChalaniController(IBaseRepository<Darta> dartaRepo, IAddressService addressService, IDartaChalaniService dartaChalaniService, IBaseRepository<ApplicationUser> userRepo, IFileHelper fileHelper, IBaseRepository<Chalani> chalaniRepo, ISequenceService sequenceService, IDateConverter dateConverter) 
        {
            _fileHelper = fileHelper;
            _dartaRepo = dartaRepo;
            _userRepo = userRepo;
            _chalaniRepo = chalaniRepo;
            _addressService = addressService;
            _dartaChalaniService = dartaChalaniService;
        }


        // GET: DartaChalani
        public ActionResult DartaList(string Name)
        {
            try
            {
                var allDarta = _dartaRepo.getAll();
                if (!string.IsNullOrEmpty(Name))
                {
                    allDarta = allDarta.Where(a => a.DartaNo.Contains(Name)).ToList();
                }
                return View(allDarta);
            }
            catch (Exception ex)
            {

                throw;
            }
        }

        public ActionResult ChalaniList(string Name)
        {
            try
            {

                var allChalani = _chalaniRepo.getAll();
                if (!string.IsNullOrEmpty(Name))
                {
                    allChalani = allChalani.Where(a => a.ChalaniNo.Contains(Name)).ToList();
                }
                return View(allChalani);
            }
            catch (Exception ex)
            {

                throw;
            }
        }


        // GET: DartaChalani/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: DartaChalani/Create
        public ActionResult CreateDartaDetail(long Id)
        {
            try
            {


                var Fatt = _addressService.GetAllfaatDropdown();
                ViewBag.Fatt = new SelectList(Fatt, "Id", "DisplayName");

                ViewBag.WardDrpDwn = from WardEnum d in Enum.GetValues(typeof(WardEnum))
                                     select new
                                     {
                                         Id = ((int)d).ToString(),
                                         DisplayName = d.GetDisplayName()
                                     };

                var provinces = _addressService.GetAllProvincedropdown();
                ViewBag.provinces = new SelectList(provinces, "Id", "DisplayName");
                var districts = _addressService.GetAllDistrictDropdown();
                ViewBag.DistrictsDrpdown = new SelectList(districts, "Id", "DisplayName");
                var Vdcs = _addressService.GetAllVdcDropdown();
                ViewBag.vdcsDrpdown = new SelectList(Vdcs, "Id", "DisplayName");

                var allUsers = _userRepo.getQueryable().Select(a => new DropdownModel { GUID = a.Id, DisplayName = a.FullNameNepali });
                ViewBag.usersDrpDown = new SelectList(allUsers, "GUID", "DisplayName");
                var model = new DartaDto();

                if (Id > 0)
                {
                    model = _dartaChalaniService.GetDartaDtoById(Id);
                }
                return View(model);
            }
            catch (CustomException ex)
            {
                return Json(new { success = false, Message = ex.Message });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, Message = "Something went wrong please contact administrator" });
            }
        }

        // POST: DartaChalani/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateDartaDetail(DartaDto darta)
        {

            try
            {

                var Fatt = _addressService.GetAllfaatDropdown();
                ViewBag.Fatt = new SelectList(Fatt, "Id", "DisplayName");

                ViewBag.WardDrpDwn = from WardEnum d in Enum.GetValues(typeof(WardEnum))
                                     select new
                                     {
                                         Id = ((int)d).ToString(),
                                         DisplayName = d.GetDisplayName()
                                     };

                var provinces = _addressService.GetAllProvincedropdown();
                ViewBag.provinces = new SelectList(provinces, "Id", "DisplayName");
                var districts = _addressService.GetAllDistrictDropdown();
                ViewBag.DistrictsDrpdown = new SelectList(districts, "Id", "DisplayName");
                var Vdcs = _addressService.GetAllVdcDropdown();
                ViewBag.vdcsDrpdown = new SelectList(Vdcs, "Id", "DisplayName");

                var allUsers = _userRepo.getQueryable().Select(a => new DropdownModel { GUID = a.Id, DisplayName = a.FullNameNepali });
                ViewBag.usersDrpDown = new SelectList(allUsers, "GUID", "DisplayName");

                if (darta.file != null)
                {
                    darta.Photo = _fileHelper.saveImageAndGetFileName(darta.file, darta.Photo);
                }
                _dartaChalaniService.AddUpdateDarta(darta);
                return RedirectToAction("DartaList");
            }
            catch(Exception ex)
            {
                return View();
            }
        }


        // GET: DartaChalani/Create
        public ActionResult CreateChalaniDetail(long Id)
        {

            try
            {
                ViewBag.WardDrpDwn = from WardEnum d in Enum.GetValues(typeof(WardEnum))
                                     select new
                                     {
                                         Id = ((int)d).ToString(),
                                         DisplayName = d.GetDisplayName()
                                     };

                var provinces = _addressService.GetAllProvincedropdown();
                ViewBag.provinces = new SelectList(provinces, "Id", "DisplayName");


               

                var districts = _addressService.GetAllDistrictDropdown();
                ViewBag.DistrictsDrpdown = new SelectList(districts, "Id", "DisplayName");

                var Vdcs = _addressService.GetAllVdcDropdown();
                ViewBag.vdcsDrpdown = new SelectList(Vdcs, "Id", "DisplayName");

                var allUsers = _userRepo.getQueryable().Select(a => new DropdownModel { GUID = a.Id, DisplayName = a.FullNameNepali });
                ViewBag.usersDrpDown = new SelectList(allUsers, "GUID", "DisplayName");
                var model = new ChalaniDto();

                if (Id > 0)
                {
                    model = _dartaChalaniService.GetChalaniDtoById(Id);
                }
                return View(model);
            }
            catch (CustomException ex)
            {
                return Json(new { success = false, Message = ex.Message });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, Message = "Something went wrong please contact administrator" });
            }
        }

        // POST: DartaChalani/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateChalaniDetail(ChalaniDto chalani)
        {

            try
            {

                ViewBag.WardDrpDwn = from WardEnum d in Enum.GetValues(typeof(WardEnum))
                                     select new
                                     {
                                         Id = ((int)d).ToString(),
                                         DisplayName = d.GetDisplayName()
                                     };

                var provinces = _addressService.GetAllProvincedropdown();
                ViewBag.provinces = new SelectList(provinces, "Id", "DisplayName");




                var districts = _addressService.GetAllDistrictDropdown();
                ViewBag.DistrictsDrpdown = new SelectList(districts, "Id", "DisplayName");

                var Vdcs = _addressService.GetAllVdcDropdown();
                ViewBag.vdcsDrpdown = new SelectList(Vdcs, "Id", "DisplayName");

                var allUsers = _userRepo.getQueryable().Select(a => new DropdownModel { GUID = a.Id, DisplayName = a.FullNameNepali });
                ViewBag.usersDrpDown = new SelectList(allUsers, "GUID", "DisplayName");

                if (chalani.file != null)
                {
                    chalani.Photo = _fileHelper.saveImageAndGetFileName(chalani.file, chalani.Photo);
                }
                _dartaChalaniService.AddUpdateChalani(chalani);



                return RedirectToAction("ChalaniList");
            }
            catch
            {

                return View(chalani);
            }
        }

        public ActionResult DeleteDarta(int id)
        {
            _dartaChalaniService.DeleteDarta(id);
            return RedirectToAction("DartaList");
        }

MunicipalityCardPrinting/WebApplication2/Views/DartaChalani/CreateChalaniDetail.cshtml
@model DTO.ChalaniDto

@{
    ViewData["Title"] = "AddUpdateChalani";
}
<h6 style="align-content:center;color:brown;margin-bottom:10px;"><u>नयाँ चलानी</u></h6>
<fieldset>
    <div class="row">
        <div class="col-md-8">
            <div class="form-row">
                <form asp-action="CreateChalaniDetail" class="form-row AddUpdateForm" enctype="multipart/form-data">

                    @Html.HiddenFor(a => a.Id)
                    <div class="col-md-4">
                        <label><b>चलानी मिति<span class="text-danger">*</span></b></label>
                        <input asp-for="ChalanidateNepali" class="form-control" id="nepali-datepicker" required="required" />
                        <span asp-validation-for="ChalanidateNepali" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label><b>प्राप्त पत्रको मिति<span class="text-danger">*</span></b></label>
                        <input asp-for="DateofReceivedLetter" class="form-control" id="nepali-datepicker1" required="required" />
                        <span asp-validation-for="DateofReceivedLetter" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label><b>पत्र पठाउने कार्यालय/ व्यक्तिको नाम<span class="text-danger">*</span></b></label>
                        <input asp-for="CompanyName" class="form-control" required="required" />
                        <span asp-validation-for="CompanyName" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label><b>प्रदेश<span class="text-danger">*</span></b></label>
                        @Html.DropDownList("AddressId", ViewBag.provinces as SelectList, "--Select--", new { @Class = "form-control" })
                        <span asp-validation-for="AddressId" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label><b>जिल्ला<span class="text-danger">*</span></b></label>
                        @Html.DropDownList("DistrictId", ViewBag.DistrictsDrpdown as SelectList, "--Select--", new { @Class = "form-control" })
                        <span asp-validation-for="DistrictId" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label><b>गाउँपालिका<span class="text-danger"></span></b></label>
                        @Html.DropDownList("VDCId", ViewBag.vdcsDrpdown as SelectList, "--Select--", new { @Class = "form-control" })
                        <span asp-validation-for="VDCId" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label><b>वार्ड<span class="text-danger"></span></b></label>
                        @Html.DropDownListFor(m => m.Ward, new SelectList(ViewBag.WardDrpDwn, "Id", "DisplayName"), "--Select--", new { @class = "form-control" })
                        <span asp-validation-for="Ward" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label><b>कम्पनीको ठेगाना (कम्पनी बिदेशी भएमा)<span class="text-danger"></span></b></label>
                        <input asp-for="CompanyAddress" class="form-control" />
                        <span asp-validation-for="CompanyAddress" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label><b>पत्रको बिषय<span class="text-danger">*</span></b></label>
                        <input asp-for="Subject" class="form-control" required="required" />
                        <span asp-validation-for="Subject" class="text-danger"></span>
                    </div>

                    <div class="col-md-4">
                        <label><b>पत्र बुझिलिने व्यक्ति<span class="text-danger"></span></b></label>
                        <input asp-for="ReceivedBy" class="form-control" />
                        <span asp-validation-for="ReceivedBy" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label><b>कैफियत<span class="text-danger"></span></b></label>
                        <input asp-for="Remarks" class="form-control" />
                        <span asp-validation-for="Remarks" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label><b>पत्रको फोटो<span class="text-danger"></span></b></label>
                        <fieldset>
                            <input name="file" class="form-control filestyle" type="file" data-classbutton="btn btn-secondary" data-classinput="form-control inline" data-icon="&lt;span class='fa fa-upload mr'&gt;&lt;/span&gt;" id="file">

                        </fieldset>
                    </div>
                    <div class="col-md-4">

                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-sm">बनाउनुहोस्</button>
                        <button type="button" class="btn btn-danger btn-sm" onclick='window.location.href="@Url.Action("ChalaniList","DartaChalani")"'>सुचिमा जानुहोस्</button>
                    </div>
                </form>
            </div>
        </div>



        <div class="col-md-4">

            <div class="card card-default">
                <div class="card-body text-center">
                    <div class="images-list images">
                        <img class="image-preview images manualimgsize" src="" alt="Photo">
                    </div>
                    <br>

                    <hr />
                    <div class="">
                        <h4 class="m-0 text-bold text-center">Preview</h4>
                        <div class="images-list images" id="previewImg">
                          
                            <img id="image" class="image-preview images manualimgsize" src="~/images/@Model.Photo" alt="" />
                         
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>

</fieldset>




@section Scripts {


    <script type="text/javascript">

     
        $("#file").change(function () {
            readURL(this);
        });
        function readURL(input) {

            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#image').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
        $(document).ready(function () {
            var mainInput = $("#nepali-datepicker");
            mainInput.nepaliDatePicker();
            var mainInput = $("#nepali-datepicker1");
            mainInput.nepaliDatePicker();
            var cmbPerProvince = $("#AddressId");
            var cmbPerDistrict = $("#DistrictId");

            cmbPerProvince.on('change', function () {
                var provinceId = cmbPerProvince.val();

                $.ajax({
                    url: "/DartaChalani/getDistrictsFromProvince?Id=" + provinceId,
                    type: "GET",
                    dataType: "json",
                    success: function (districts) {
                        $('#DistrictId > option').remove();
                        $.each(districts, function (i, district) {
                            console.log(district);
                            $('#DistrictId').append('<option value=' + district.Id + '>' + district.DisplayName + '</option>');

                        });
                        cmbPerDistrict.change();
                    },
                    error: function () {
                        new ToastMessage("Choose Valid Province");
                        console.log("failed to retrieve data.");
                    }
                });

            });


            cmbPerDistrict.on('change', function () {

                var districtId = cmbPerDistrict.val();
                $.ajax({
                    url: "/DartaChalani/getVdcsFromDistrict?Id=" + districtId,
                    type: "GET",
                    dataType: "json",
                    success: function (vdcs) {
                        $('#VDCId > option').remove();
                        $.each(vdcs, function (i, vdc) {
                            $('#VDCId').append('<option value=' + vdc.Id + '>' + vdc.DisplayName + '</option>');
                        });
                    },
                    error: function () {
                        new ToastMessage("Choose Valid District");
                        console.log("failed to retrieve data.");
                    }
                });
            });


        });

     


    </script>
}

MunicipalityCardPrinting/WebApplication2/Views/DartaChalani/CreateDartaDetail.cshtml
@model DTO.DartaDto

@{
    ViewData["Title"] = "AddUpdateDartaCard";
}
<h6 style="align-content:center;color:brown;margin-bottom:10px;"><u>नयाँ दर्ता</u></h6>
<fieldset>
    <div class="row">
        <div class="col-md-8">
            <div class="form-row">


                <form asp-action="CreateDartaDetail" enctype="multipart/form-data"  class="form-row AddUpdateForm">
                    <div asp-validation-summary="ModelOnly" class="text-danger" ></div>


                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    @Html.HiddenFor(a => a.Id)



                    <div class="col-md-4">
                        <label><b>दर्ता मिति<span class="text-danger">*</span></b></label>
                        <input asp-for="Dartadate" class="form-control nepali-calendar" id="nepali-datepicker" required="required" />
                        <span asp-validation-for="Dartadate" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label><b>पत्र पठाउने कार्यालयको नाम<span class="text-danger">*</span></b></label>
                        <input asp-for="CompanyName" class="form-control" required="required"/>
                        <span asp-validation-for="CompanyName" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label><b>प्रदेश<span class="text-danger">*</span></b></label>
                        @Html.DropDownList("AddressId", ViewBag.provinces as SelectList, "--Select--", new { @Class = "form-control" })
                        <span asp-validation-for="AddressId" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label><b>जिल्ला<span class="text-danger">*</span></b></label>
                        @Html.DropDownList("DistrictId", ViewBag.DistrictsDrpdown as SelectList, "--Select--", new { @Class = "form-control" })
                        <span asp-validation-for="DistrictId" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label><b>गाउँपालिका<span class="text-danger">*</span></b></label>
                        @Html.DropDownList("VDCId", ViewBag.vdcsDrpdown as SelectList, "--Select--", new { @Class = "form-control" })
                        <span asp-validation-for="VDCId" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label><b>वार्ड<span class="text-danger">*</span></b></label>
                        @Html.DropDownListFor(m => m.Ward, new SelectList(ViewBag.WardDrpDwn, "Id", "DisplayName"), "--Select--", new { @class = "form-control" })
                        <span asp-validation-for="Ward" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label><b>कम्पनीको ठेगाना (कम्पनी बिदेशी भएमा)<span class="text-danger"></span></b></label>
                        <input asp-for="CompanyAddress" class="form-control" />
                    </div>
                    <div class="col-md-4">
                        <label><b>प्राप्त पत्रको चलानी नम्बर<span class="text-danger"></span></b></label>
                        <input asp-for="ReferenceNo" class="form-control" />
                        <span asp-validation-for="ReferenceNo" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label><b>प्राप्त पत्रको मिति<span class="text-danger">*</span></b></label>
                        <input asp-for="DateofReceivedLetter" class="form-control nepali-calendar" id="nepali-datepicker1" required="required" />
                        <span asp-validation-for="DateofReceivedLetter" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label><b>बिषय<span class="text-danger">*</span></b></label>
                        <input asp-for="Subject" class="form-control" />
                        <span asp-validation-for="Subject" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label><b>फाट<span class="text-danger">*</span></b></label>
                        @Html.DropDownList("Faat", ViewBag.Fatt as SelectList, "--Select--", new { @class = "form-control" })
                        <span asp-validation-for="Faat" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label><b>कैफियत<span class="text-danger"></span></b></label>
                        <input asp-for="Remarks" class="form-control" />
                        <span asp-validation-for="Remarks" class="text-danger"></span>
                    </div>
                    <div class="col-md-4">
                        <label><b>पत्रको फोटो<span class="text-danger"></span></b></label>
                        <fieldset>

                            <input name="file" class="form-control filestyle" type="file" data-classbutton="btn btn-secondary" data-classinput="form-control inline" data-icon="&lt;span class='fa fa-upload mr'&gt;&lt;/span&gt;" id="file">

                        </fieldset>
                    </div>
                    <div class="col-md-4">

                    </div>
                    <div class="col-md-4">

                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-sm">बनाउनुहोस्</button>
                        <button type="button" class="btn btn-danger btn-sm" onclick='window.location.href="@Url.Action("DartaList","DartaChalani")"'>सुचिमा जानुहोस्</button>
                    </div>
                </form>
            </div>
        </div>



        <div class="col-md-4">

            <div class="card card-default">
                <div class="card-body text-center">
                    <div class="images-list images">
                        <img class="image-preview images manualimgsize" src="" alt="Photo">
                    </div>
                    <br>

                    <hr />
                    <div class="">
                        <h4 class="m-0 text-bold text-center">Preview</h4>
                        <div class="images-list images" id="previewImg">
                           
                                <img id="image" class="image-preview images manualimgsize" src="~/images/@Model.Photo" alt="" />
                          

                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
  
</fieldset>

@section Scripts {


    <script type="text/javascript">


        $("#file").change(function () {
            readURL(this);
        });
        function readURL(input) {

            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#image').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
        $(document).ready(function () {
            var mainInput = $("#nepali-datepicker");
            mainInput.nepaliDatePicker();
            var cmbPerProvince = $("#AddressId");
            var cmbPerDistrict = $("#DistrictId");

            cmbPerProvince.on('change', function () {
                var provinceId = cmbPerProvince.val();

                $.ajax({
                    url: "/DartaChalani/getDistrictsFromProvince?Id=" + provinceId,
                    type: "GET",
                    dataType: "json",
                    success: function (districts) {
                        $('#DistrictId > option').remove();
                        $.each(districts, function (i, district) {
                            console.log(district);
                            $('#DistrictId').append('<option value=' + district.Id + '>' + district.DisplayName + '</option>');

                        });
                        cmbPerDistrict.change();
                    },
                    error: function () {
                        new ToastMessage("Choose Valid Province");
                        console.log("failed to retrieve data.");
                    }
                });

            });


            cmbPerDistrict.on('change', function () {

                var districtId = cmbPerDistrict.val();
                $.ajax({
                    url: "/DartaChalani/getVdcsFromDistrict?Id=" + districtId,
                    type: "GET",
                    dataType: "json",
                    success: function (vdcs) {
                        $('#VDCId > option').remove();
                        $.each(vdcs, function (i, vdc) {
                            $('#VDCId').append('<option value=' + vdc.Id + '>' + vdc.DisplayName + '</option>');
                        });
                    },
                    error: function () {
                        new ToastMessage("Choose Valid District");
                        console.log("failed to retrieve data.");
                    }
                });
            });
            var mainInput = $("#nepali-datepicker1");
            mainInput.nepaliDatePicker();

        });


    </script>
}

MunicipalityCardPrinting/WebApplication2/Views/DartaChalani/GetChalaniListOfSevenDays.cshtml
@model IEnumerable<Infrastructure.Database.Models.Chalani>
@{ ViewData["Title"] = "चलानी सुची"; Layout = "~/Views/Shared/_Layout.cshtml"; }
<section class="content-header">
    <h1>
        @ViewData["Title"]
    </h1>
</section>
<section class="content">
    <div class="box box-default">
        <div class="box-header">
            <div class="row">
                <div class="col-lg-1">
                    <a href="/DartaChalani/CreateChalaniDetail/0" class="btn btn-primary btn-md ">
                        <i class="fa fa-plus-circle"></i>नयाँ चलानी
                    </a>
                </div>
            </div>
        </div>
        <table class="table" border="1">

            <tr style="background-color: #3c8dbc;color:white">

                <th>
                    सि.नं.
                </th>
                <th>
                    चलानी मिति
                </th>
                <th>
                    पत्र संख्या
                </th>
                <th>
                    पत्र पठाउने कार्यालय / व्यक्तिको नाम
                </th>
                <th>
                    बिषय
                </th>
                <th>
                    पत्र बुझिलिने व्यक्ति
                </th>
                @*<th> Action</th>*@
            </tr>
            <tbody>
                @{ var i = 1;
                    if (Model != null && Model.Any())
                    {
                        foreach (var item in Model)
                        {
                            <tr>

                                <td>
                                    @Html.DisplayFor(x => i)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ChalanidateNepali)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ChalaniNo)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CompanyName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Subject)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ReceivedBy)
                                </td>
                                @*<td>
                                    @Html.ActionLink("Edit", "CreateChalaniDetail", new { id = item.Id })

                                    @Html.ActionLink("Delete", "DeleteChalani", new { id = item.Id }, new { onclick = "return confirm('Are you sure want to delete this item?')" })

                                </td>*@
                            </tr>
                            i++;
                        }
                    }
                    else
                    {
                        <tr style="text-align:center; color:red"><td colspan="10"><b>No Record Found</b></td></tr>
                    }
                }
            </tbody>
        </table>
    </div>
</section>