MunicipalityCardPrinting/WebApplication2/Controllers/FattController.cs
using Business.Services.Interface;
using DTO;
using Infrastructure.Database.Models;
using Infrastructure.Repositories.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MunicipalityCardPrinting.Controllers
{
    [Authorize]
    public class FattController : Controller
    {

        private readonly IFattService _fattService;
        private readonly IBaseRepository<Fatt> _fattRepository;

        public FattController(IFattService fattService, IBaseRepository<Fatt> _fattRepository)
        {
            this._fattService = fattService;
            this._fattRepository = _fattRepository;
        }

        public IActionResult Index()
        {
           var data= _fattService.getAllFattDetails();
            return View(data);
        }

        public IActionResult AddUpdateFatt(long id)
        {

            var fatt = new FattDto();
             if (id > 0)
            {
                fatt=_fattService.GetByFattId(id);
            }
            return View(fatt);
        }

        [HttpPost]
        public IActionResult AddUpdateFatt(FattDto fattdto)
        {
            try
            {
                if (fattdto.id > 0)
                {
                    _fattService.UpdateFatt(fattdto);
                }
                else
                {
                    _fattService.AddFatt(fattdto);
                }
                 
                return RedirectToAction("index");
            }
            catch (Exception)
            {

                throw;
            }
        }

        public IActionResult DeleteFatt(FattDto fattDto)
        {
            if (fattDto.id > 0)
            {
                _fattService.DeleteFatt(fattDto);
                return RedirectToAction("Index");
            }
            return View();
            
        }
    }
}

MunicipalityCardPrinting/WebApplication2/Views/Fatt/AddUpdateFatt.cshtml
@model DTO.FattDto

<h4>फाट</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddUpdateFatt">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden>
                <label asp-for="id" class="control-label"></label>
                <input asp-for="id" class="form-control" />
                <span asp-validation-for="id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label><b>फाटको नाम<span class="text-danger">*</span></b></label>
                <input asp-for="FattName" class="form-control" required="required"/>
                <span asp-validation-for="FattName" class="text-danger"></span>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary btn-sm">बनाउनुहोस्</button>
                <button type="button" class="btn btn-danger btn-sm" onclick='window.location.href="@Url.Action("Index","Fatt")"'>सुचिमा जानुहोस्</button>
            </div>
        </form>
    </div>
</div>

MunicipalityCardPrinting/WebApplication2/Views/Fatt/Index.cshtml
@model IEnumerable<DTO.FattDto>
@{ ViewData["Title"] = "फाँट सुची"; Layout = "~/Views/Shared/_Layout.cshtml"; }
<section class="content-header">
    <h1>
        @ViewData["Title"]
    </h1>
</section>
<section class="content">
    <div class="box box-default">
        <div class="box-header">
            <div class="row">
                <div class="col-lg-1">
                    <a href="/Fatt/AddUpdateFatt" class="btn btn-primary btn-md ">
                        <i class="fa fa-plus-circle"></i>नयाँ फाँट
                    </a>
                </div>
            </div>
        </div>
        <table class="table" border="1">

            <tr style="background-color: #3c8dbc;color:white">

                <th>
                    SN
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FattName)
                </th>
                <th>Action</th>
            </tr>

            <tbody>
                @{ var i = 1;
                    if (Model != null && Model.Any())
                    {
                        foreach (var item in Model)
                        {
                            <tr>

                                <td>
                                    @Html.DisplayFor(x => i)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.FattName)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "AddUpdateFatt", new { id = item.id })

                                    @Html.ActionLink("Delete", "DeleteFatt", new { id = item.id }, new { onclick = "return confirm('Are you sure want to delete this item?')" })

                                </td>
                            </tr>
                            i++;
                        }
                    }
                    else
                    {
                        <tr style="text-align:center; color:red"><td colspan="6"><b>No Record Found</b></td></tr>
                    }
                }
            </tbody>
        </table>
    </div>
</section>