MunicipalityCardPrinting/WebApplication2/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Infrastructure.Database.Models;
using Infrastructure.Repositories.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MunicipalityCardPrinting.Utils;

namespace MunicipalityCardPrinting.Controllers
{
    [Authorize]
    public class ReportController : Controller
    {

        private readonly IBaseRepository<Darta> _dartaRepo;
        private readonly IBaseRepository<Chalani> _chalaniRepo;
        private readonly IDateConverter _dateConverter;


        public ReportController(IBaseRepository<Darta> dartaRepo,  IBaseRepository<Chalani> chalaniRepo, IDateConverter dateConverter)
        {
            _dartaRepo = dartaRepo;
            _chalaniRepo = chalaniRepo;
            _dateConverter = dateConverter;
          
        }
        public IActionResult Index()
        {
            return View();
        }

        public ActionResult DartaList(string from_date, string to_date)
        {
            try
            {


                var allDarta = _dartaRepo.getQueryable();


                


                if (from_date != null)
                {
                    //var replacedata = from_date.Replace('-', '/');
                    var english_From_date = _dateConverter.ToAD(from_date);
                    allDarta = allDarta.Where(a => a.DartadateEnglish >= english_From_date);
                }
                if (to_date != null)
                {
                    var english_To_date = _dateConverter.ToAD(to_date);
                    allDarta = allDarta.Where(a => a.DartadateEnglish <= english_To_date);
                }
                return View(allDarta.ToList());
            }
            catch (Exception ex)
            {

                throw;
            }
        }

        public ActionResult ChalaniList(string? from_date, string? to_date)
        {
            try
            {
                var allChalani = _chalaniRepo.getQueryable();

                
                

                if (from_date != null)
                {
                    var english_From_date = _dateConverter.ToAD(from_date);
                    allChalani = allChalani.Where(a => a.Chalanidate >= english_From_date);
                }
                if (to_date != null)
                {
                    var english_To_date = _dateConverter.ToAD(to_date);
                    allChalani = allChalani.Where(a => a.Chalanidate <= english_To_date);
                }
                return View(allChalani.ToList());
            }
            catch (Exception ex)
            {

                throw;
            }
        }

        
    }
}

MunicipalityCardPrinting/WebApplication2/Views/Report/ChalaniList.cshtml
@model IEnumerable<Infrastructure.Database.Models.Chalani>
@{ ViewData["Title"] = "चलानी रिपोर्ट"; Layout = "~/Views/Shared/_Layout.cshtml"; }
<section class="content-header">
    <h1>
        @ViewData["Title"]
    </h1>
</section>
<section class="content">
    <div class="box box-default">

         <div class="col-lg-11">
                    <form asp-action="DartaList" asp-controller="Report" method="get">

                        <div class="row">
                            <div class="col-lg-10">
                                <div class="row">
                                   @* <div class="col-lg-3">
                                        <input name="Name" placeholder="Search By Darta Number" type="text" class="form-control" style="width:115%; margin-left:40px" />
                                    </div>*@

                                     <div class="col-lg-3">
                                        <input name="from_date"  type="text"  placeholder="From date" class="form-control  nepali-calendar" id="nepali-datepicker" style="width:100%;" />
                                    </div>
                                    <div class="col-lg-3">
                                        <input name="to_date" type="text" placeholder="To date" class="form-control  nepali-calendar" id="nepali-datepicker1" style="width:100%;" />
                                    </div>




                                    <div class="col-lg-3">
                                        <button type="submit" class="btn btn-success btn-md" style="margin-left:40px">
                                            <span class="fa fa-filter"></span> Filter
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
        <table class="table" border="1">

            <tr style="background-color: #3c8dbc;color:white">

                <th>
                    सि.नं.
                </th>
                <th>
                    चलानी मिति
                </th>
                <th>
                    पत्र संख्या
                </th>
                <th>
                    पत्र पठाउने कार्यालय / व्यक्तिको नाम
                </th>
                <th>
                    बिषय
                </th>
                <th>
                    पत्र बुझिलिने व्यक्ति
                </th>
            </tr>
            <tbody>
                @{ var i = 1;
                    if (Model != null && Model.Any())
                    {
                        foreach (var item in Model)
                        {
                                <tr>

                                    <td>
                                        @Html.DisplayFor(x => i)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ChalanidateNepali)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ChalaniNo)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CompanyName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Subject)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ReceivedBy)
                                    </td>
                                </tr>
                            i++;
                        }
                    }
                    else
                    {
                        <tr style="text-align:center; color:red"><td colspan="10"><b>No Record Found</b></td></tr>
                    }
                }
            </tbody>
        </table>
    </div>
</section>

@section scripts{
    <script type='text/javascript'>

        $(document).ready(function(){
            var mainInput = $("#nepali-datepicker");
            mainInput.nepaliDatePicker();

            var mainInput = $("#nepali-datepicker1");
            mainInput.nepaliDatePicker();
        });

        

    </script>
}

MunicipalityCardPrinting/WebApplication2/Views/Report/DartaList.cshtml
@model IEnumerable<Infrastructure.Database.Models.Darta>
@{ ViewData["Title"] = "दर्ता रिपोर्ट"; Layout = "~/Views/Shared/_Layout.cshtml"; }
<section class="content-header">
    <h1>
        @ViewData["Title"]
    </h1>
</section>
<section class="content">
    <div class="box box-default">


         <div class="col-lg-11">
                    <form asp-action="DartaList" asp-controller="Report" method="get">

                        <div class="row">
                            <div class="col-lg-10">
                                <div class="row">
                                   @* <div class="col-lg-3">
                                        <input name="Name" placeholder="Search By Darta Number" type="text" class="form-control" style="width:115%; margin-left:40px" />
                                    </div>*@

                                     <div class="col-lg-3">
                                        <input name="from_date"  type="text" placeholder="From date" class="form-control nepali-calendar" id="nepali-datepicker" style="width:100%;" />
                                    </div>
                                    <div class="col-lg-3">
                                        <input name="to_date" type="text" placeholder="To date" class="form-control nepali-calendar" id="nepali-datepicker1" style="width:100%;" />
                                    </div>


                                    <div class="col-lg-3">
                                        <button type="submit" class="btn btn-success btn-md" style="margin-left:40px">
                                            <span class="fa fa-filter"></span> Filter
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>


        <table class="table" border="1">

            <tr style="background-color: #3c8dbc;color:white">

                <th>
                    सि.नं.
                </th>
                <th>
                    दर्ता मिति
                </th>
                <th>
                    पत्र पठाउने कार्यालयको नाम
                </th>
                <th>
                    प्राप्त पत्रको चलानी नम्बर
                </th>
                <th>
                    बिषय
                </th>
                <th>
                    फाट
                </th>
            </tr>
            <tbody>
                @{ var i = 1;
                    if (Model != null && Model.Any())
                    {
                        foreach (var item in Model)
                        {
                                <tr>

                                    <td>
                                        @Html.DisplayFor(x => i)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Dartadate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CompanyName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ReferenceNo)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Subject)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Fatt.FattName)
                                    </td>
                                </tr>
                            i++;
                        }
                    }
                    else
                    {
                        <tr style="text-align:center; color:red"><td colspan="7"><b>No Record Found</b></td></tr>
                    }
                }
            </tbody>
        </table>
    </div>
</section>


@section scripts{
    <script type='text/javascript'>

        $(document).ready(function(){
            var mainInput = $("#nepali-datepicker");
            mainInput.nepaliDatePicker();

            var mainInput = $("#nepali-datepicker1");
            mainInput.nepaliDatePicker();
        });

        

    </script>
}